version: "3"

services:
  api:
    ports:
      - "8000:8000"
    build:
      context: ./api
      dockerfile: ./Dockerfile
  app:
    ports:
      - "3000:80"
    build:
      context: ./app
      dockerfile: ./Dockerfile
  web:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ./app/static:/usr/share/nginx/html

# Define a network, which allows containers to communicate
# with each other, by using their container name as a hostname
networks:
  app_network:
    external: true
